Repository Pic-me-Pic-me/pic.me-client, pull requests merged in 2023-04, with the labels that each got.

#206 [ Flower-Currentvote ] 꽃인상 현재 투표 API 연결
  src/components/CurrentVote/CurrentVoteBtn.tsx
  src/components/CurrentVote/CurrentVoteInfo.tsx
  src/components/CurrentVote/Layout/CurrentVoteInfoLayout.tsx
  src/components/Share/Layout/ShareLayout.tsx
  src/components/common/Router.tsx
  src/lib/hooks/useGetFlowerVoteDetail.tsx
  src/pages/CurrentFlowerDetail.tsx
  src/pages/Share.tsx
  src/recoil/maker/atom.ts
  src/types/vote.ts
Labels: 📝 Code review, CurrrnetVote

#198 [flower-library] 꽃인상 테스트 라이브러리
  src/asset/icon/ic_libraryFlower.svg
  src/asset/icon/index.ts
  src/components/Library/EndedVoting.tsx
  src/components/Library/MonthVoting.tsx
  src/pages/Library.tsx
  src/types/library.ts
Labels: 📝 Code review

#204 [Maker_Voting] 꽃.ver 투표 생성
  src/asset/icon/ic_cropImg.svg
  src/asset/icon/ic_modify.svg
  src/asset/icon/ic_removeImg.svg
  src/components/Layout/maker/MakerVotingLayout.tsx
  src/components/Voting/maker/CoachMark.tsx
  src/components/Voting/maker/ImageCrop.tsx
  src/components/Voting/maker/ImageInput.tsx
  src/components/Voting/maker/TitleInput.tsx
  src/components/common/ImageForm.tsx
Labels: 📤 Maker_Voting

#205 [ Player_Voting ] 꽃 인상 투표 API 연결
  src/asset/icon/IcChoice.svg
  src/components/Landing/VoteLanding.tsx
  src/components/Voting/player/KeyWordTag.tsx
  src/components/Voting/player/StickerResultVoting.tsx
  src/components/Voting/player/StickerVoting.tsx
  src/constant/FlowerIconList.js
  src/constant/playerInfo.ts
  src/pages/PlayerLanding.tsx
  src/pages/player/flower/KeyWordVoting.tsx
  src/types/vote.ts
  src/utils/jsonGetStickerList.ts
Labels: 📥 Player_Voting

#211 [ flower-result] 꽃인상 테스트 결과페이지
  src/asset/icon/ic_stickerOff.svg
  src/asset/icon/ic_stickerOn.svg
  src/asset/icon/index.ts
  src/components/Library/EndedVoting.tsx
  src/components/Library/MonthVoting.tsx
  src/components/common/Router.tsx
  src/constant/FlowerIconList.js
  src/lib/hooks/useGetFlowerVoteResult.tsx
  src/pages/FlowerResult.tsx
  src/styles/style.d.ts
  src/styles/theme.ts
  src/types/vote.ts
Labels: 📝 Code review

#215 Hotfix/213 -> develop-flower
  src/lib/hooks/useGetFlowerVoteDetail.tsx
  src/pages/CurrentFlowerDetail.tsx
  src/recoil/maker/atom.ts
Labels: Hotfix
